//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ManagementSystem.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaDongHang { get; set; }
        public int MaSanPham { get; set; }
        public int MaKhachHang { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public int Gia { get; set; }
        public string MaKhuyenMai { get; set; }
        public int TinhTrang { get; set; }
        public int CachThanhToan { get; set; }
        public int isDelete { get; set; }
    
        public virtual CachThanhToan CachThanhToan1 { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual TinhTrang TinhTrang1 { get; set; }
    }
}
