//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ManagementSystem.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public int MaLoaiSanPham { get; set; }
        public int GiaGoc { get; set; }
        public int GiaBan { get; set; }
        public int SoLuongConLai { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> isDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
